services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vrchat-asset-manager
    ports:
      - "5000:5000"
    volumes:
      - ./database:/app/database
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    # Run as node user
    user: "node"